[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "birdnetpy"
version = "0.1.6"
description = "A lightweight Python library for identifying bird species from live audio or pre-recorded files using the BirdNET model."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
authors = [{name="Simon Holliday", email="simon.holliday@protonmail.com"}]
keywords = ["birdnet", "bird", "species", "identification", "bioacoustics", "ornithology", "wildlife", "audio", "sound", "detection", "tflite", "machine-learning", "conservation", "ecology", "raven", "audacity"]
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Science/Research",
	"Topic :: Scientific/Engineering :: Bio-Informatics",
	"Topic :: Multimedia :: Sound/Audio :: Analysis",
]

dependencies = [
	"librosa",
	"numba",
	"numpy<2",
	"sounddevice",
	"soundfile",
	"ai-edge-litert",
]

[project.optional-dependencies]
dev = [
	"mypy==1.15.0",
]

[project.scripts]
birdcatcher = "birdnetpy.cli:main"

[tool.setuptools]
package-dir = {""="src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
birdnetpy = [
	"birdnet/*.tflite",
	"birdnet/*.txt",
	"*.txt",
]

[tool.mypy]
ignore_missing_imports = true

[project.urls]
Homepage = "https://github.com/simonholliday/BirdNET-Py"
Repository = "https://github.com/simonholliday/BirdNET-Py"
