[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "birdnetpy"
version = "0.1.6"
description = "A lightweight Python library for identifying bird species from live audio or pre-recorded files using the BirdNET model."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7,<3.12"
authors = [{name="Simon Holliday", email="si@untitledwork.com"}]

dependencies = [
	"librosa",
	"numba",
	"numpy<2",
	"sounddevice",
	"soundfile",
	"tflite-runtime",
]

[project.optional-dependencies]
dev = [
	"mypy==1.15.0",
]

[project.scripts]
birdnetpy = "birdnetpy.cli:main"

[tool.setuptools]
package-dir = {""="src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
birdnetpy = [
	"birdnet/*.tflite",
	"birdnet/*.txt",
	"*.txt",
]

[tool.mypy]
ignore_missing_imports = true

[project.urls]
Homepage = "https://github.com/simonholliday/BirdNET-Py"
Repository = "https://github.com/simonholliday/BirdNET-Py"
